name: Scratch Studio Members
on:
  #schedule:
    #- cron: "0 12 * * *"
  workflow_dispatch:
  
jobs:
  Scratch_Studio_Members:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 curators.py
      - run: git config user.name 'github-actions[bot]'
      - run: git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: git commit -m 'Github Actions Update File' -a
      - run: git push
